source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'bootstrap-sass', '~> 2.3.2.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
  gem 'annotate', '2.5.0'
end

group :test do
  gem 'capybara', '1.1.2'
  gem 'minitest'
  
  gem 'guard-spork', '1.2.0'
  gem 'childprocess', '0.3.6'
  gem 'spork', '0.9.2'
  
  # Test gems on Macintosh OS X
  gem 'rb-fsevent', '0.9.1', :require => false
  gem 'growl', '1.0.3'
  
  # Test gems on Linux
  #gem 'rb-inotify', '0.8.8'
  #gem 'libnotify', '0.5.9'
  
  # Test gems on Windows
  #gem 'rb-fchange', '0.0.5'
  #gem 'rb-notifu', '0.0.4'
  #gem 'win32console', '1.3.0'
  
end

group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
